
name: CI

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_KEY }}'

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v1
      # with:
        # version: '390.0.0'
        # service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud info

    # Build the Docker image
    - name: Build and Push
      run: |
        IMAGE=gcr.io/ilia456/echo:stable
        docker build -t gcr.io/ilia456/echo:stable -f Dockerfile .
        docker push gcr.io/ilia456/echo:stable

